# ------------------------------------------------
# docker-compose for ModelPolisher development
# run gradle devel first and then docker-compose -f docker-compose.devel.yml run ... or export COMPOSE_FILE and run normally 
# ------------------------------------------------
version: '3'
services:
  biggdb:
    image: mephenor/bigg_docker:1.5
    container_name: modelpolisher_biggdb
    ports:
      - 1310:5432
  adb:
    image: mephenor/adb_docker:0.1.1
    container_name: modelpolisher_adb
    ports:
      - 1013:5432
  polisher:
    build: ./docker/java_docker
    container_name: modelpolisher_java    
    depends_on:
      - biggdb
      - adb
    stdin_open: true
    tty: true
